spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bakery
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    user:
      name: admin
      password: 1234
      roles: ADMIN

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
